// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://znuxhpimzpbgjmrkjkka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpudXhocGltenBiZ2ptcmtqa2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUzOTE2MDAsImV4cCI6MjA1MDk2NzYwMH0.5_8tvpGskTPXPGP5200Uik6J-pfN1SP6K-kXDqTMplE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);